image: maven:3.6.3-jdk-11

pipelines:
  branches:
    FinalWebAutomation:
      # -  step:
      #     script:
      #       - pipe: atlassian/trigger-pipeline:5.0.0
      #         variables:
      #           BITBUCKET_USERNAME: $BITBUCKET_USER
      #           BITBUCKET_APP_PASSWORD: $BITBUCKET_PASSWORD
      #           #ACCOUNT: 'Asset Peoppl'
      #           REPOSITORY: "nirogstreet"
      #           REF_TYPE: "branch"
      #           REF_NAME: "master"
      #           CUSTOM_PIPELINE_NAME: "schedule deploy to automation"
      #           WAIT: "true"
      - step:
          name: deploy config to terminator
          script:
            - pipe: atlassian/rsync-deploy:0.5.0
              variables:
                USER: $SSH_USER
                SERVER: $SSH_SERVER
                REMOTE_PATH: "/root/testing/"
                LOCAL_PATH: "config/"
    
      - step:
          name: Moving locator to config
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SSH_SERVER
                COMMAND: "cd /root/testing/ && pwd && mkdir config && mv NirogStreetLocator.properties /root/testing/config/ "

      - step:
          name: deploy src to testing folder
          script:
            - pipe: atlassian/rsync-deploy:0.5.0
              variables:
                USER: $SSH_USER
                SERVER: $SSH_SERVER
                REMOTE_PATH: "/root/testing/"
                LOCAL_PATH: "src"
    
      - step:
          name: Build
          caches:
            - maven
          script:
            #- cd scripts
            #- sh restore_db.sh
            #- cd ..
            #- mvn -version
            - mvn clean compile assembly:single
            #- clean install -Dtest=TestngTestRunnerTest.java -DfailIfNoTests=false
            #- mvn test 
            #- mvn package Dtest=TestngTestRunnerTest.java -DfailIfNoTests=false
            #- mvn clean install 
            #- mvn clean install test -DsuiteXmlFile="testng.xml"
            - ls -R $DEPLOYMENT_DIR
          artifacts: # defining the artifacts to be passed to each future step.
            - "**/target/*.jar"
          after-script:
            - ls -R $DEPLOYMENT_DIR
            - pipe: atlassian/rsync-deploy:0.5.0
              variables:
                USER: $SSH_USER
                SERVER: $SSH_SERVER
                REMOTE_PATH: "/root/testing/"
                LOCAL_PATH: "$DEPLOYMENT_DIR/target/*.jar"
                DEBUG: "true"
          
      - step:
          name: Run Testcase and send Report
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SSH_SERVER
                COMMAND: "cd /root/testing/ && pwd && DISPLAY=:1 xvfb-run java -jar standalone-jar-with-dependencies.jar"
                timeout: ${PIPELINE_BUILD_TIMEOUT}
          after-script:
            - ALERT_TYPE="success"
            - if [[ $BITBUCKET_EXIT_CODE -ne 0 ]]; then ALERT_TYPE="error" ; fi
            - pipe: atlassian/email-notify:0.5.0
              variables:
                USERNAME: "dev.napses@gmail.com"
                PASSWORD: $MAIL_PASSWORD
                FROM: "dev.napses@gmail.com"
                TO: "automation@jiraaf.com"
                HOST: "smtp.gmail.com"
                SUBJECT: "Bitbucket Pipe Notification for your-bitbucket-brunch"
                BODY_PLAIN: "The Build is $(ALERT_TYPE) For ${BITBUCKET_BRANCH} Branch Genrated an IP :http://216.48.178.193:8080/ui/#login"

  # custom:
  #   run-functional-test-on-uat:
  #     - step:
  #         script:
  #           - pipe: atlassian/trigger-pipeline:5.0.0
  #             variables:
  #               BITBUCKET_USERNAME: $BITBUCKET_USER
  #               BITBUCKET_APP_PASSWORD: $BITBUCKET_PASSWORD
  #               REPOSITORY: "nirogstreet"
  #               REF_TYPE: "branch"
  #               REF_NAME: "uat"
  #               CUSTOM_PIPELINE_NAME: "deploy-to-automation"
  #               WAIT: "true"
  #     - step:
  #         name: deploy config to terminator
  #         script:
  #           - pipe: atlassian/rsync-deploy:0.5.0
  #             variables:
  #               USER: $SSH_USER
  #               SERVER: $SSH_SERVER
  #               REMOTE_PATH: "$TESTING/config"
  #               LOCAL_PATH: "config/"
  #     - step:
  #         name: Build
  #         caches:
  #           - maven
  #         script:
  #           - cd scripts
  #           - sh restore_db.sh
  #           - cd ..
  #           #- mvn -version
  #           - mvn clean compile assembly:single
  #           - ls -R $DEPLOYMENT_DIR
  #         artifacts: # defining the artifacts to be passed to each future step.
  #           - "**/target/*.jar"
  #         after-script:
  #           - ls -R $DEPLOYMENT_DIR
  #           - pipe: atlassian/rsync-deploy:0.5.0
  #             variables:
  #               USER: $SSH_USER
  #               SERVER: $SSH_SERVER
  #               REMOTE_PATH: "$TESTING"
  #               LOCAL_PATH: "$DEPLOYMENT_DIR/target/*.jar"
  #               DEBUG: "true"
  #     - step:
  #         name: Run Testcase and send Report
  #         script:
  #           - pipe: atlassian/ssh-run:0.2.2
  #             variables:
  #               SSH_USER: $SSH_USER
  #               SERVER: $SSH_SERVER
  #               COMMAND: "cd $TESTING && pwd && java -jar standalone-jar-with-dependencies.jar"
  #         after-script:
  #           - ALERT_TYPE="success"
  #           - if [[ $BITBUCKET_EXIT_CODE -ne 0 ]]; then ALERT_TYPE="error" ; fi
  #           - pipe: atlassian/email-notify:0.5.0
  #             variables:
  #               USERNAME: "dev.napses@gmail.com"
  #               PASSWORD: $MAIL_PASSWORD
  #               FROM: "dev.napses@gmail.com"
  #               TO: "automation@jiraaf.com"
  #               HOST: "smtp.gmail.com"
  #               SUBJECT: "Bitbucket Pipe Notification for your-bitbucket-brunch"
  #               BODY_PLAIN: "The Build is $(ALERT_TYPE) For ${BITBUCKET_BRANCH} Branch Genrated an IP :http://216.48.178.193:8080/ui/#login"

  #   run-functional-test-on-qa:
  #     - step:
  #         script:
  #           - pipe: atlassian/trigger-pipeline:5.0.0
  #             variables:
  #               BITBUCKET_USERNAME: $BITBUCKET_USER
  #               BITBUCKET_APP_PASSWORD: $BITBUCKET_PASSWORD
  #               REPOSITORY: "nirogstreet"
  #               REF_TYPE: "branch"
  #               REF_NAME: "QA"
  #               CUSTOM_PIPELINE_NAME: "deploy-to-automation"
  #               WAIT: "true"
  #     - step:
  #         name: deploy config to terminator
  #         script:
  #           - pipe: atlassian/rsync-deploy:0.5.0
  #             variables:
  #               USER: $SSH_USER
  #               SERVER: $SSH_SERVER
  #               REMOTE_PATH: "$TESTING/config"
  #               LOCAL_PATH: "config/"
  #     - step:
  #         name: Build
  #         caches:
  #           - maven
  #         script:
  #           - cd scripts
  #           - sh restore_db.sh
  #           - cd ..
  #           #- mvn -version
  #           - mvn clean compile assembly:single
  #           - ls -R $DEPLOYMENT_DIR
  #         artifacts: # defining the artifacts to be passed to each future step.
  #           - "**/target/*.jar"
  #         after-script:
  #           - ls -R $DEPLOYMENT_DIR
  #           - pipe: atlassian/rsync-deploy:0.5.0
  #             variables:
  #               USER: $SSH_USER
  #               SERVER: $SSH_SERVER
  #               REMOTE_PATH: "$TESTING"
  #               LOCAL_PATH: "$DEPLOYMENT_DIR/target/*.jar"
  #               DEBUG: "true"
  #     - step:
  #         name: Run Testcase and send Report
  #         script:
  #           - pipe: atlassian/ssh-run:0.2.2
  #             variables:
  #               SSH_USER: $SSH_USER
  #               SERVER: $SSH_SERVER
  #               COMMAND: "cd $TESTING && pwd && java -jar standalone-jar-with-dependencies.jar"
  #         after-script:
  #           - ALERT_TYPE="success"
  #           - if [[ $BITBUCKET_EXIT_CODE -ne 0 ]]; then ALERT_TYPE="error" ; fi
  #           - pipe: atlassian/email-notify:0.5.0
  #             variables:
  #               USERNAME: "dev.napses@gmail.com"
  #               PASSWORD: $MAIL_PASSWORD
  #               FROM: "dev.napses@gmail.com"
  #               TO: "automation@jiraaf.com"
  #               HOST: "smtp.gmail.com"
  #               SUBJECT: "Bitbucket Pipe Notification for your-bitbucket-brunch"
  #               BODY_PLAIN: "The Build is $(ALERT_TYPE) For ${BITBUCKET_BRANCH} Branch Genrated an IP :http://216.48.178.193:8080/ui/#login"

  #   schedule-to-test-master: #12 AM schedule pipeline
  #     - step:
  #         script:
  #           - pipe: atlassian/trigger-pipeline:5.0.0
  #             variables:
  #               BITBUCKET_USERNAME: $BITBUCKET_USER
  #               BITBUCKET_APP_PASSWORD: $BITBUCKET_PASSWORD
  #               REPOSITORY: "jiraaf"
  #               REF_TYPE: "branch"
  #               REF_NAME: "feature/automation_master"
  #               CUSTOM_PIPELINE_NAME: "deploy-to-automation"
  #               WAIT: "true"
  #     - step:
  #         name: deploy config to terminator
  #         script:
  #           - pipe: atlassian/rsync-deploy:0.5.0
  #             variables:
  #               USER: $SSH_USER
  #               SERVER: $SSH_SERVER
  #               REMOTE_PATH: "$TESTING/config"
  #               LOCAL_PATH: "config/"
  #     - step:
  #         name: Build
  #         caches:
  #           - maven
  #         script:
  #           - cd scripts
  #           - sh restore_db.sh
  #           - cd ..
  #           #- mvn -version
  #           - mvn clean compile assembly:single
  #           - ls -R $DEPLOYMENT_DIR
  #         artifacts: # defining the artifacts to be passed to each future step.
  #           - "**/target/*.jar"
  #         after-script:
  #           - ls -R $DEPLOYMENT_DIR
  #           - pipe: atlassian/rsync-deploy:0.5.0
  #             variables:
  #               USER: $SSH_USER
  #               SERVER: $SSH_SERVER
  #               REMOTE_PATH: "$TESTING"
  #               LOCAL_PATH: "$DEPLOYMENT_DIR/target/*.jar"
  #               DEBUG: "true"
  #     - step:
  #         name: Run Testcase and send Report
  #         script:
  #           - pipe: atlassian/ssh-run:0.2.2
  #             variables:
  #               SSH_USER: $SSH_USER
  #               SERVER: $SSH_SERVER
  #               COMMAND: "cd $TESTING && pwd && java -jar standalone-jar-with-dependencies.jar"
  #         after-script:
  #           - ALERT_TYPE="success"
  #           - if [[ $BITBUCKET_EXIT_CODE -ne 0 ]]; then ALERT_TYPE="error" ; fi
  #           - pipe: atlassian/email-notify:0.5.0
  #             variables:
  #               USERNAME: "dev.napses@gmail.com"
  #               PASSWORD: $MAIL_PASSWORD
  #               FROM: "dev.napses@gmail.com"
  #               TO: "automation@jiraaf.com"
  #               HOST: "smtp.gmail.com"
  #               SUBJECT: "Bitbucket Pipe Notification for your-bitbucket-brunch"
  #               BODY_PLAIN: "The Build is $(ALERT_TYPE) For ${BITBUCKET_BRANCH} Branch Genrated an IP :http://216.48.178.193:8080/ui/#login"
